### ISSUE TITLE
Error when using Motion v2 plugin

### ISSUE THREAD

**Issue by amandaradtke** [bodymovin/bodymovin#157]
Hey!

I've animated a set of six icons, and I'm getting errors with two of them. The thing that they have in common is that they use the Burst effect from Mt. Mograph's Motion v2 plugin. It generates a shape layer with expressions tied to slider controls on that layer. I saw a previous response that said errors can occur with expressions tied to hidden layers, but as far as I can tell, that isn't happening here.

I can animate the burst without the plugin if needed, but I'd love to make it work if possible!

ERROR: 

Uncaught TypeError: Cannot read property 'position' of undefined

ERROR: 

jQuery.Deferred exception: Cannot read property 'position' of undefined TypeError: Cannot read property 'position' of undefined
    at n.fn (eval at initiateExpression (http://URL/scripts.js:10:240), <anonymous>:3:52)
    at n.execute [as getValue] (http://URL/scripts.js:9:31476)
    at t [as getValue] (http://URL/scripts.js:5:28588)
    at IShapeElement.BaseElement.prepareFrame (http://URL/scripts.js:6:29440)
    at SVGRenderer.renderFrame (http://URL/scripts.js:6:10286)
    at AnimationItem.renderFrame (http://URLscripts.js:9:16345)
    at AnimationItem.gotoFrame (http://URL/scripts.js:9:16249)
    at AnimationItem.checkLoaded (http://URL/scripts.js:9:15769)
    at AnimationItem.t (http://URL/scripts.js:9:15275)
    at AnimationItem.waitForFontsLoaded (http://URL/scripts.js:9:15348)

**Comment by bodymovin** [comment]
can you share the .ae project so I can take a look?

**Comment by amandaradtke** [comment]
Here you go!
https://www.dropbox.com/s/v3k8aixuo0j8m8h/2016-09-22_COTM_Digital%20Portal%20Icons.aep?dl=0

**Comment by bodymovin** [comment]
Hi, there are a couple of things that are not yet supported by the plugin.
The position error is fixed and I will upload it to gihub this weekend.
But unfortunately repeaters and roving across time are not yet supported and it will take me some time to implement them.

**Comment by amandaradtke** [comment]
Ah, I see! Thanks for checking on this!
