### ISSUE TITLE
bodymovin.js errors when using import and running tests in Jasmine

### ISSUE THREAD

**Issue by ningbit** [bodymovin/bodymovin#173]
This is the error I'm seeing when using ES6 import into my project. I don't have to call the 'bodymovin' function, it will error as it runs through the code.

C:\bodymovin_project\node_modules\bodymovin\build\player\bodymovin.js:12401
};var bodymovinjs = {}; function play(animation){ animationManager.play(animation); } function pause(animation){ animationManager.pause(animation); } function togglePause(animation){ animationManager.togglePause(animation); } function setSpeed(value,animation){ animationManager.setSpeed(value, animation); } function setDirection(value,animation){ animationManager.setDirection(value, animation); } function stop(animation){ animationManager.stop(animation); } function moveFrame(value){ animationManager.moveFrame(value); } function searchAnimations(){ if(standalone === true){ animationManager.searchAnimations(animationData,standalone, renderer); }else{ animationManager.searchAnimations(); } } function registerAnimation(elem){ return animationManager.registerAnimation(elem); } function resize(){ animationManager.resize(); } function start(){ animationManager.start(); } function goToAndStop(val,isFrame, animation){
 
TypeError: Cannot read property 'src' of undefined
    at C:\bodymovin_project\node_modules\bodymovin\build\player\bodymovin.js:12401:3247
    at svgNS (C:\bodymovin_project\node_modules\bodymovin\build\player\bodymovin.js:1:233)
    at Object.<anonymous> (C:\bodymovin_project\node_modules\bodymovin\build\player\bodymovin.js:1:284)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\bodymovin_project\node_modules\babel-core\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
[nodemon] app crashed - waiting for file changes before starting...

Here is a possible fix, add an undefined check to ln 1240:
var queryString = typeof myScript !== 'undefined' ? myScript.src.replace(/^[^\?]+\??/,'') : '';

**Comment by Aprillion** [comment]
I get the same problem (using in Jest), even if I have no tests and only `import` 1 component that itself imports `bodymovin` (4.5.4):

```
    TypeError: Cannot read property 'src' of undefined

      at node_modules/bodymovin/build/player/bodymovin.js:12748:3246
      at Object.<anonymous>.svgNS (node_modules/bodymovin/build/player/bodymovin.js:1:260)
      at Object.<anonymous> (node_modules/bodymovin/build/player/bodymovin.js:1:311)
```

**Comment by trevorwhealy** [comment]
`import bodymovin`

```
 FAIL  public/js/components/__tests__/component.js
  ● Test suite failed to run
    TypeError: Cannot read property 'src' of undefined

      at node_modules/bodymovin/build/player/bodymovin.js:13375:3246
      at svgNS (node_modules/bodymovin/build/player/bodymovin.js:1:260)
      at Object.<anonymous> (node_modules/bodymovin/build/player/bodymovin.js:1:311)
      at Object.<anonymous> (public/js/components/component.js:3:44)
      at Object.<anonymous> (public/js/components/__tests__/component.js:9:25)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:87:13)
      at process.emit (events.js:172:7)
      at internal/child_process.js:721:12
      at nextTickCallbackWith0Args (node.js:436:9)
      at process._tickCallback (node.js:365:13)
