### ISSUE TITLE
animation.json does not render correctly on Android

### ISSUE THREAD

**Issue by arshujain** [bodymovin/bodymovin#394]
I add the lottie library to my project and placed the animation.json file in assets folder as mentioned on the github. 
But it is showing the error :-1: 
 E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: com.example.arshuj.lottieproject, PID: 14554
                  java.lang.RuntimeException: An error occured while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference
                      at com.airbnb.lottie.LottieComposition$Factory.parseLayers(LottieComposition.java:200)
                      at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:194)
                      at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:163)
                      at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:17)
                      at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:7)
                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                      at java.lang.Thread.run(Thread.java:818) 

Kindly help to run this json file.
I just  replaced the name of the file in sample code mentioned.

protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_lottie);

        LottieAnimationView animationView = (LottieAnimationView) findViewById(R.id.animation_view);
        animationView.setAnimation("animation.json");
        animationView.loop(true);
        animationView.playAnimation();
    }

Only "hello world.json" is replaced with "animation.json".

**Comment by bodymovin** [comment]
Hi, can you pass this issue to the Lottie team?
